---
# tasks file for dhcp-svr package installation

- name: Install DHCP server apt packages
  become: true
  apt:
    update_cache: true
    name: isc-dhcp-server
    state: present
  notify: start dhcpd
